### ISSUE TITLE
Summer 2020 courses are not available

### ISSUE THREAD

**Issue by dimonoid** [morinted/schedule-generator#48]

**Comment by davidschlachter** [comment]
The web scraper has been hitting some error since the new schedules went up. I'll take a look and hopefully have a fix by Wednesday.

**Comment by dimonoid** [comment]
Thanks

**Comment by davidschlachter** [comment]
The error appeared to be intermittent and schedules updated automatically on April 9th. They should continue updating automatically every four days, results visible at https://schlachter.ca/schedgen/

For future reference, the problem was:
````
Traceback (most recent call last):
  File "updateDatabase.py", line 354, in <module>
    main()
  File "updateDatabase.py", line 188, in main
    b.find_element_by_id(year).click()
  File "/home/david/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/david/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/david/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/david/.local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <input type="checkbox" name="UO_PUB_SRCH_WRK_SSR_RPTCK_OPT_03$0" id="UO_PUB_SRCH_WRK_SSR_RPTCK_OPT_03$0" class="PSCHECKBOX" tabindex="71" value="Y" onclick="setupTimeout2();    this.form.UO_PUB_SRCH_WRK_SSR_RPTCK_OPT_03$chk$0.value=(this.checked?'Y':'N');doFocus_win0(this,false,true);"> is not clickable at point (282, 462). Other element would receive the click: <div class="ps_modalmask psc_hidden" id="pt_modalMask" style="height: 953px; width: 808px; display: block;">...</div>
````
